points:
  - [-4.491859436035156,-3.441661834716797,0.5]
  - [-5.491859436035156,-7.441661834716797,0.5]
  - [1.7864766120910645,-8.31071662902832,0.5]
  - [4.737040042877197,-7.575063705444336,0.5]
  - [2.503446578979492,-1.8579827547073364,0.5]
  - [7.2615227699279785,0.922993540763855,0.5]
  - [5.784129619598389,3.008725643157959,0.5]
  - [7.924177169799805,7.223642349243164,0.5]
  - [3.388796091079712,8.081833839416504,0.5]
  - [1.4605804681777954,-1.9448882341384888,0.5]
  - [-1.1248581409454346,-0.48922109603881836,0.5]
  - [-0.10371840000152588,8.440319061279297,0.5]
  - [-7.642770767211914,6.919472694396973,0.5]
  - [-4.5141730308532715,3.117357015609741,0.5]
  - [-8.229382514953613,-1.8579829931259155,0.5]
  - [-2.971599817276001,-2.6835851669311523,0.5]
  - [-4.491859436035156,-3.441661834716797,0.5]
